import { HelpCircle, Sparkles, Brain, CreditCard, Shield, Settings, Users } from 'lucide-react';

// FAQ data with rich metadata for enhanced features
export const faqData = [
  { id: 1, category: 'getting-started', question: 'How do I get started with IAM?', answer: 'Getting started is simple! Sign up for a free account, verify your email, and you can immediately begin recording and transcribing meetings. No credit card required for the free tier. Our onboarding wizard will guide you through your first transcription in under 5 minutes.', tags: ['signup', 'onboarding', 'free trial'], helpful: { yes: 245, no: 12 }, relatedIds: [2, 8] },
  { id: 2, category: 'getting-started', question: 'What file formats do you support for uploads?', answer: 'We support all major audio and video formats including MP3, WAV, M4A, MP4, MOV, and AVI. Our platform automatically converts files for optimal transcription. The maximum file size is 2GB for premium users and 500MB for free accounts.', tags: ['file formats', 'upload', 'audio', 'video'], helpful: { yes: 189, no: 8 }, relatedIds: [3, 6] },
  { id: 3, category: 'getting-started', question: 'Can I record directly in the browser?', answer: 'Yes! Our advanced browser-based recording system uses cutting-edge Web Audio APIs to capture high-quality audio directly from your microphone, without needing additional software.', tags: ['browser recording', 'microphone', 'web audio'], helpful: { yes: 312, no: 15 }, relatedIds: [1, 2] },
  { id: 4, category: 'transcription', question: 'How accurate are your transcriptions?', answer: 'Our AI achieves 95%+ accuracy using advanced OpenAI Whisper technology with multi-provider fallbacks. Accuracy can reach 99%+ for professional recordings. We also support South African accents and terminology.', tags: ['accuracy', 'AI', 'whisper', 'south african'], helpful: { yes: 567, no: 23 }, relatedIds: [5, 6] },
  { id: 5, category: 'transcription', question: 'Do you support speaker identification?', answer: 'Yes! Our advanced AI can identify and label different speakers in your recordings. This feature, known as diarization, is perfect for meetings, interviews, and panel discussions.', tags: ['speaker identification', 'diarization', 'multiple speakers'], helpful: { yes: 234, no: 11 }, relatedIds: [4, 18] },
  { id: 6, category: 'transcription', question: 'How long does transcription take?', answer: 'Typically, a 1-hour recording takes 5-10 minutes to process. Premium users get priority processing and real-time progress updates via WebSocket connections.', tags: ['processing time', 'speed', 'real-time'], helpful: { yes: 198, no: 9 }, relatedIds: [4, 10] },
  { id: 7, category: 'transcription', question: 'Can I export transcripts in different formats?', answer: 'Absolutely! Export your transcripts as PDF, DOCX, TXT, SRT (subtitles), or JSON. Each format is optimized for different use cases, from sharing to development.', tags: ['export', 'formats', 'PDF', 'DOCX', 'SRT'], helpful: { yes: 276, no: 7 }, relatedIds: [14] },
  { id: 8, category: 'pricing', question: 'What\'s included in the free plan?', answer: 'Our free plan includes 3 transcription hours per month, basic features, and full access to our web application. It\'s perfect for trying out the service or for light usage.', tags: ['free plan', 'limitations', 'trial'], helpful: { yes: 445, no: 18 }, relatedIds: [9, 10] },
  { id: 9, category: 'pricing', question: 'How does billing work for South African customers?', answer: 'We support local South African payment methods including EFT via Stitch and card payments via PayGate. All pricing is in ZAR (Rand), and subscriptions are billed monthly with no long-term contracts.', tags: ['south african billing', 'ZAR', 'payment methods', 'EFT'], helpful: { yes: 156, no: 4 }, relatedIds: [8, 10] },
  { id: 10, category: 'pricing', question: 'Can I upgrade or downgrade my plan anytime?', answer: 'Yes! Change your plan anytime from your account dashboard. Upgrades take effect immediately, while downgrades apply at your next billing cycle. Unused transcription hours don\'t roll over.', tags: ['plan changes', 'upgrade', 'downgrade', 'billing cycle'], helpful: { yes: 289, no: 12 }, relatedIds: [8, 9] },
  { id: 11, category: 'security', question: 'Is IAM POPIA compliant?', answer: 'Yes! We are fully compliant with South Africa\'s Protection of Personal Information Act (POPIA). We implement data minimization, obtain proper consent, and provide full data subject rights.', tags: ['POPIA', 'compliance', 'privacy', 'data protection'], helpful: { yes: 378, no: 6 }, relatedIds: [12, 13] },
  { id: 12, category: 'security', question: 'How is my audio data protected?', answer: 'Your audio files are encrypted with AES-256 at rest and TLS 1.3 in transit. Files are stored securely in Wasabi S3 with 99.999999999% durability and are automatically deleted after 90 days unless you choose to keep them.', tags: ['encryption', 'security', 'data storage', 'retention'], helpful: { yes: 412, no: 8 }, relatedIds: [11, 13] },
  { id: 13, category: 'security', question: 'Who has access to my transcriptions?', answer: 'Only you and team members you explicitly invite have access. Our staff cannot view your content unless you grant support access. All access is logged and auditable through your security dashboard.', tags: ['access control', 'privacy', 'team access', 'audit logs'], helpful: { yes: 267, no: 5 }, relatedIds: [11, 17] },
  { id: 14, category: 'technical', question: 'Do you offer an API for developers?', answer: 'Yes! Our RESTful API supports all major transcription features. We provide comprehensive documentation, SDKs for popular languages, and webhook support for real-time updates.', tags: ['API', 'developers', 'webhooks', 'SDK'], helpful: { yes: 523, no: 14 }, relatedIds: [7, 15] },
  { id: 15, category: 'technical', question: 'What are your uptime guarantees?', answer: 'We maintain 99.9% uptime with comprehensive monitoring via Prometheus and Grafana. Our infrastructure uses auto-scaling on Railway/DigitalOcean with multi-region fallbacks for maximum reliability.', tags: ['uptime', 'SLA', 'reliability', 'monitoring'], helpful: { yes: 189, no: 7 }, relatedIds: [14, 16] },
  { id: 16, category: 'technical', question: 'How do you handle system outages?', answer: 'Our multi-provider architecture ensures continuity. If OpenAI Whisper experiences issues, we automatically failover to Azure or Google Speech APIs. Real-time status updates are available on our status page.', tags: ['failover', 'redundancy', 'status page', 'incident management'], helpful: { yes: 234, no: 9 }, relatedIds: [15] },
  { id: 17, category: 'collaboration', question: 'How do team features work?', answer: 'Team plans allow you to invite colleagues, share transcriptions, assign roles (Admin, Editor, Viewer), and collaborate. Team admins can manage billing, user access, and view usage analytics.', tags: ['teams', 'collaboration', 'roles', 'sharing'], helpful: { yes: 345, no: 11 }, relatedIds: [13, 18] },
  { id: 18, category: 'collaboration', question: 'Can multiple people edit the same transcript?', answer: 'Yes! Our real-time collaborative editor allows multiple team members to edit transcripts simultaneously. Changes are synchronized instantly via WebSockets, with conflict resolution and version history.', tags: ['collaborative editing', 'real-time', 'version history'], helpful: { yes: 278, no: 8 }, relatedIds: [5, 17] },
];

// Category configuration with icons and styling
export const categories = [
  { id: 'all', name: 'All', icon: HelpCircle, color: 'from-blue-500 to-blue-600' },
  { id: 'getting-started', name: 'Getting Started', icon: Sparkles, color: 'from-emerald-500 to-emerald-600' },
  { id: 'transcription', name: 'Transcription', icon: Brain, color: 'from-purple-500 to-purple-600' },
  { id: 'pricing', name: 'Pricing & Plans', icon: CreditCard, color: 'from-amber-500 to-amber-600' },
  { id: 'security', name: 'Security & Privacy', icon: Shield, color: 'from-red-500 to-red-600' },
  { id: 'technical', name: 'Technical', icon: Settings, color: 'from-indigo-500 to-indigo-600' },
  { id: 'collaboration', name: 'Teams', icon: Users, color: 'from-pink-500 to-pink-600' }
];



